### ISSUE TITLE
sudo systemctl restart docker failed

### ISSUE THREAD

**Issue by beyondli** [NVIDIA/egx-platform#1]
hi：
env:
    xavier, JP4.4

error is :
![image](https://user-images.githubusercontent.com/11239010/88940776-c4756780-d2ba-11ea-8617-4b5cdd9854ad.png)

when I run sudo systemctl restart docker , it failed, if I set "default-runtime" : "nvidia" at daemon.json
but if I remove the "default-runtime" : "nvidia" at daemon.json, no error occurs.
thanks for any help

**Comment by moconnor725** [comment]
+container-dev

**Comment by beyondli** [comment]
> container-dev

hi moconnor725 ,
thanks for your reply!

I try :sudo apt install container-dev, but can't find this command. and I searched it on web， no more results can hint me 
thanks for any help!

**Comment by beyondli** [comment]
> > container-dev
> 
> hi moconnor725 ,
> thanks for your reply!
> 
> I try :sudo apt install container-dev, but can't find this command. and I searched it on web， no more results can hint me
> thanks for any help!

hi moconnor725 
I found the error,
I missed the ',' before "default-runtime" : "nvidia".
now it can run OK, thanks!

**Comment by moconnor725** [comment]
Just looked at the issue on github and it appears the issue has been resolved. Can someone with admin access on the repo, close it please.
________________________________
Von: Michael O'Connor (Deep Learning) <michaelo@nvidia.com>
Gesendet: Donnerstag, 30. Juli 2020 17:51
An: NVIDIA/egx-platform <reply@reply.github.com>; NVIDIA/egx-platform <egx-platform@noreply.github.com>; container-dev <container-dev@exchange.nvidia.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [NVIDIA/egx-platform] sudo systemctl restart docker failed (#1)


+container-dev

**Comment by angudadevops** [comment]
@beyondli Thanks for the confirmation. Closing the issue.
