### ISSUE TITLE
Can it be installed in jetson nano or AGX xavier?

### ISSUE THREAD

**Issue by JustinhoCHN** [NVIDIA/egx-platform#2]
Can I install this full stack in jetson nano or xavier device?

**Comment by swarren** [comment]
The following may be helpful:
https://github.com/NVIDIA/egx-platform/blob/master/install-guides/Jetson_Xavier_NX_v2.0.md

I don't work on this project, so I don't know the status of the install guide.

**Comment by beyondli** [comment]
hi JustinhoCHN：
this guide can be run on jetson after I test on xavier

**Comment by JustinhoCHN** [comment]
@beyondli thank you, I'll try
