### ISSUE TITLE
 kubeadm init failed

### ISSUE THREAD

**Issue by wpf19911118** [NVIDIA/egx-platform#3]
using this command：

sudo kubeadm init  --kubernetes-version=v1.17.5   --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=Swap

log as：
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
	- 'docker ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
inspur@inspur-desktop:~$ docker ps -a | grep kube | grep -v pause
37ffc3b5e519        fe3d691efbf3                                       "kube-controller-man…"   1 second ago             Created                                                 k8s_kube-controller-manager_kube-controller-manager-inspur-desktop_kube-system_7158f0b27236f6415eb7355a7e8c9f00_12
65dfa9955714        303ce5db0e90                                       "etcd --advertise-cl…"   2 seconds ago            Created                                                 k8s_etcd_etcd-inspur-desktop_kube-system_266e3cbe15890ca893ce1a3189d0b9bc_12
7ed40b88bed5        f648efaff966                                       "kube-scheduler --au…"   2 seconds ago            Created                                                 k8s_kube-scheduler_kube-scheduler-inspur-desktop_kube-system_b95be9ddff954501b1709fd9f2e0a160_11
2df386c10608        f640481f6db3                                       "kube-apiserver --ad…"   3 seconds ago            Created                                                 k8s_kube-apiserver_kube-apiserver-inspur-desktop_kube-system_4433de2f50862654422c69416687939f_14
a7a9c2339dee        303ce5db0e90                                       "etcd --advertise-cl…"   29 seconds ago           Created                                                 k8s_etcd_etcd-inspur-desktop_kube-system_266e3cbe15890ca893ce1a3189d0b9bc_11
539bc5e2e4e4        f640481f6db3                                       "kube-apiserver --ad…"   30 seconds ago           Created                                                 k8s_kube-apiserver_kube-apiserver-inspur-desktop_kube-system_4433de2f50862654422c69416687939f_13
b3923c474abc        fe3d691efbf3                                       "kube-controller-man…"   33 seconds ago           Created                                                 k8s_kube-controller-manager_kube-controller-manager-inspur-desktop_kube-system_7158f0b27236f6415eb7355a7e8c9f00_11
fc745bf1b74b        f648efaff966                                       "kube-scheduler --au…"   40 seconds ago           Created                                                 k8s_kube-scheduler_kube-scheduler-inspur-desktop_kube-system_b95be9ddff954501b1709fd9f2e0a160_10

**Comment by angudadevops** [comment]
@wpf19911118 , Could you please try sudo kubeadm reset --force and retry the init

**Comment by angudadevops** [comment]
as comment is pending since long time, closing it. Please re open if you still have an issue
