### ISSUE TITLE
how to compile devicequery?

### ISSUE THREAD

**Issue by beyondli** [NVIDIA/egx-platform#4]
guide  followed
===================
Now compile the cuda examples to validate from pod.

$ cd /usr/local/cuda/samples/1_Utilities/deviceQuery
$ sudo make
$ cd ~
====================
where to compile it? kubectl just apply yml to create container from docker image. 
compile from docker images?

**Comment by angudadevops** [comment]
@beyondli we believe you followed Jetson Xavier Guide. 
Did you install the Jetpack, it should comes with cuda samples. ?

**Comment by angudadevops** [comment]
As comment is pending long time, closing the comment.
