### ISSUE TITLE
Task in v3.0 Ubuntu 20.04 installation playbook has both shell and command module calls

### ISSUE THREAD

**Issue by kjw3** [NVIDIA/egx-platform#5]
- name: Taint the Kubernetes Control Plane node
     when: "'running' not in k8sup.stdout"
     command: kubectl taint nodes --all node-role.kubernetes.io/master-
     shell: command -v helm >/dev/null 2>&1
     register: helm_exists
     ignore_errors: yes

Results in following error:
Installing EGX Stack
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! conflicting action statements: command, shell

The error appears to be in '/home/ubuntu/egx-platform/playbooks/egx-installation.yaml': line 252, column 6, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   - name: Taint the Kubernetes Control Plane node
     ^ here

**Comment by angudadevops** [comment]
it's fixed, please validate and let us know
